name: pl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.0.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - aom=3.3.0
  - async-timeout=4.0.2
  - attrs=21.4.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.3.29
  - cachetools=5.0.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - click=8.1.2
  - colorama=0.4.4
  - cryptography=36.0.2
  - cudatoolkit=10.2.89
  - ffmpeg=5.0.1
  - freetype=2.11.0
  - frozenlist=1.3.0
  - fsspec=2022.3.0
  - future=0.18.2
  - gettext=0.21.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=2.6.2
  - google-auth-oauthlib=0.4.6
  - grpcio=1.45.0
  - icu=70.1
  - idna=3.3
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - jbig=2.1
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libdeflate=1.10
  - libdrm=2.4.109
  - libffi=3.2.1
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpciaccess=0.16
  - libpng=1.6.37
  - libprotobuf=3.20.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.18.0
  - libtiff=4.3.0
  - libunistring=0.9.10
  - libuv=1.43.0
  - libva=2.14.0
  - libvpx=1.11.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.14
  - libxml2=2.9.12
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - markdown=3.3.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - ncurses=6.3
  - nettle=3.7.3
  - ninja=1.10.2
  - numpy=1.21.2
  - numpy-base=1.21.2
  - oauthlib=3.2.0
  - openh264=2.1.1
  - openssl=1.1.1n
  - packaging=21.3
  - pillow=9.0.1
  - pip=22.0.4
  - protobuf=3.20.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pydeprecate=0.3.2
  - pyjwt=2.3.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pysocks=1.7.1
  - python=3.8.0
  - python_abi=3.8
  - pytorch=1.11.0
  - pytorch-lightning=1.6.0
  - pytorch-mutex=1.0
  - pyu2f=0.1.5
  - pyyaml=6.0
  - readline=8.1.2
  - requests=2.27.1
  - requests-oauthlib=1.3.1
  - rsa=4.8
  - setuptools=59.5.0
  - six=1.16.0
  - sqlite=3.38.2
  - svt-av1=0.9.1
  - tensorboard=2.8.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tk=8.6.12
  - torchaudio=0.11.0
  - torchmetrics=0.7.3
  - torchvision=0.12.0
  - tqdm=4.64.0
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - urllib3=1.26.9
  - werkzeug=2.1.1
  - wheel=0.37.1
  - x264=1!161.3030
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.7.2
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.2
  - zipp=3.8.0
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - albumentations==1.1.0
    - alembic==1.7.7
    - cloudpickle==2.0.0
    - databricks-cli==0.16.6
    - docker==5.0.3
    - entrypoints==0.4
    - flask==2.1.1
    - gitdb==4.0.9
    - gitpython==3.1.27
    - greenlet==1.1.2
    - gunicorn==20.1.0
    - imageio==2.16.1
    - importlib-resources==5.6.0
    - itsdangerous==2.1.2
    - jinja2==3.1.1
    - joblib==1.1.0
    - jsonargparse==4.5.0
    - mako==1.2.0
    - markupsafe==2.1.1
    - mlflow==1.24.0
    - networkx==2.7.1
    - opencv-python==4.5.5.64
    - opencv-python-headless==4.5.5.64
    - pandas==1.4.2
    - prometheus-client==0.14.0
    - prometheus-flask-exporter==0.20.0
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pywavelets==1.3.0
    - qudida==0.0.4
    - querystring-parser==1.2.4
    - scikit-image==0.19.2
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - smmap==5.0.0
    - sqlalchemy==1.4.34
    - sqlparse==0.4.2
    - tabulate==0.8.9
    - threadpoolctl==3.1.0
    - tifffile==2022.3.25
    - timm==0.5.4
    - websocket-client==1.3.2
